### ISSUE TITLE
Incorrect version of NGINX Deprecated 

### ISSUE THREAD

**Issue by absoluteZero87** [cloudfoundry/nginx-buildpack#137]
What version of the buildpack you are using?
v1 .1.38

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy NGINX

What did you expect to happen?
NGINX Deployed

What was the actual behavior?
Deploy NGINX Failed due to deprecation warnings

---------
In the manifest.yml
```
dependency_deprecation_dates:
- version_line: 1.20.x
  name: nginx
  date: 2022-05-25
  link: https://nginx.org/
- version_line: 1.21.x
  name: nginx
  date: 2022-05-25
  link: https://nginx.org/
```

It appears that version 1.21.X has been deprecated
however I believe 1.21.6 is the latest version of NGINX
