### ISSUE TITLE
cflinuxfs4: Build dependency & update buildpack develop

### ISSUE THREAD

**Issue by brayanhenao** [cloudfoundry/nginx-buildpack#188]
### A/C

* [Dependencies build pipeline](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/) should build all dependencies required for [nginx v2b](https://github.com/cloudfoundry/nginx-buildpack) to run on cflinuxfs4.

* The buildpack's `manifest.yml` on the develop branch must contain all the dependencies built in step 1 validating the next instructions:

  * For the `any_stacks` dependencies, the `manifest.yml` should contain an entry like this:

```
- name: dep
  uri: https://buildpacks.cloudfoundry.org/dependencies/dep/dep-1.2.3-any-stack-abcdef.tar.gz
  cf_stacks:
  - cflinuxfs3
  - cflinuxfs4
```

  * For the specific cflinxufs4 build dependencies, the `manifest.yml` should contain entries like this:

```
- name: dep
  uri: https://buildpacks.cloudfoundry.org/dependencies/dep/dep-1.2.3-cflinuxfs3-abcdef.tar.gz
  cf_stacks:
  - cflinuxfs3
- name: dep
  uri: https://buildpacks.cloudfoundry.org/dependencies/dep/dep-1.2.3-cflinuxfs4-abcdef.tar.gz
  cf_stacks:
  - cflinuxfs4
```

* Dependency version lines that are known not to work with cflinuxfs4 must be excluded.

4. On develop, when I run integration tests with [test config](https://github.com/cloudfoundry/nginx-buildpack/blob/v1.1.45/config.json#L2) set to `cflinuxfs4` stack, it should pass.

### Proposal

**Build dependency and update buildpack develop**

* Follow the guide https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Add-cflinuxfs4-support-for-a-Buildpack
